### ISSUE TITLE
Roadmap for CRAN release

### ISSUE THREAD

**Issue by psolymos** [psolymos/intrval#1]
- [x] set of functions to finalize (naming etc)
- [x] support functions to finalize: use a single function for `x %[]% c(a,b)` types only, print & plot.
- [x] separate help files for `%[]%` and `%[o]%` operators
- [x] improve testing suite: unit tests + random interval testing
- [x] updated `README` file
- [x] tweet/blog when done
